# Generated by Django 5.0.2 on 2024-02-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.TextField(max_length=3000, verbose_name='Reglamento'),
        ),
    ]
