# Generated by Django 5.0.2 on 2024-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('image', models.ImageField(null=True, upload_to='users/images/', verbose_name='Imagen')),
                ('points', models.IntegerField(max_length=10, verbose_name='Puntaje')),
            ],
        ),
    ]
