# Generated by Django 5.0.2 on 2024-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='tournaments/players/images/', verbose_name='Imagen'),
        ),
    ]
