# Generated by Django 5.0.2 on 2024-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='tournaments/images/players/profile/', verbose_name='Imagen'),
        ),
    ]
