# Generated by Django 5.0.2 on 2024-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('details', models.CharField(max_length=500, verbose_name='Detalles')),
                ('status', models.BooleanField(verbose_name='Activo')),
                ('image', models.ImageField(null=True, upload_to='tournaments/images/games/', verbose_name='Imagen')),
            ],
        ),
    ]
