# Generated by Django 5.0.2 on 2024-02-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game',
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(verbose_name='Puntaje'),
        ),
    ]
