# Generated by Django 5.0.2 on 2024-02-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_tournament_options_alter_tournament_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
