# Generated by Django 5.0.2 on 2024-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_rename_user_player_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='UIDGame',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, verbose_name='UID'),
        ),
    ]
