# Generated by Django 5.0.2 on 2024-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('online', 'En curso'), ('ended', 'Finalizado')], default='C', max_length=7, verbose_name='Estado'),
        ),
    ]
