# Generated by Django 5.0.2 on 2024-03-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_remove_tournament_uidgame_game_uidgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='imageURL',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link Imagen Firestore'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° participantes'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='uidRegister',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UID Firestore'),
        ),
    ]
