# Generated by Django 5.0.2 on 2024-07-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_alter_tournament_avalaible_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='avalaible_points',
        ),
    ]
