# Generated by Django 5.0.2 on 2024-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_remove_tournament_avalaible_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='avalaible_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puntaje disponible'),
        ),
    ]
